# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import helloworld_pb2 as proto_dot_helloworld__pb2


class GreeterStub(object):
  """函数
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SayHello = channel.unary_unary(
        '/Greeter/SayHello',
        request_serializer=proto_dot_helloworld__pb2.HelloRequest.SerializeToString,
        response_deserializer=proto_dot_helloworld__pb2.HelloReply.FromString,
        )
    self.SendPeople = channel.unary_unary(
        '/Greeter/SendPeople',
        request_serializer=proto_dot_helloworld__pb2.PeopleRequest.SerializeToString,
        response_deserializer=proto_dot_helloworld__pb2.IsCorrect.FromString,
        )


class GreeterServicer(object):
  """函数
  """

  def SayHello(self, request, context):
    """入参是 message HelloRequest 这个格式，出参是 message HelloRequest 这个格式
    通过不同函数的调用来传参
    用这个的好处在于，免除自己压缩dict为二进制、再自己发送数据的麻烦
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendPeople(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayHello': grpc.unary_unary_rpc_method_handler(
          servicer.SayHello,
          request_deserializer=proto_dot_helloworld__pb2.HelloRequest.FromString,
          response_serializer=proto_dot_helloworld__pb2.HelloReply.SerializeToString,
      ),
      'SendPeople': grpc.unary_unary_rpc_method_handler(
          servicer.SendPeople,
          request_deserializer=proto_dot_helloworld__pb2.PeopleRequest.FromString,
          response_serializer=proto_dot_helloworld__pb2.IsCorrect.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
